tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Pivotal.vscode-spring-boot@1.17.0:mGdRFTP1eLVuk7lwGhEWRg==
    - vscjava.vscode-spring-initializr@0.4.6:WOgtgIwX3Ngy4pM9ArXjCQ==
    - mlazzarini.pair-programming-timer@0.3.1:o4SdfEP9e4a3DqNe+OFjpQ==
    - vscjava.vscode-java-test@0.22.3:r0wZhaCeRHUpyUd2S8C/Tw==
    - vscjava.vscode-maven@0.21.2:eUANtFfmlMMlJemdLOZs4A==
    - redhat.vscode-quarkus@1.5.0:w7xQsEjV+6/Tn2l7bIqfhg==